# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: A Reporter
author: Roger Erismann
copyright: "2024"

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: 'off'
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_engine              : pdflatex  
  use_jupyterbook_latex     : true 

html:
  html_show_copyright: false
  language: en
  use_download_button: false
  use_repository_button: true
  use_issues_button: true

repository:
  url: https://github.com/hammerdirt-analyst/feb_2024  # The URL to your book's repository
  branch: main
  
sphinx:
  extra_extensions: 
    - myst_nb
    





