name: demoassistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pydantic
  - scikit-learn
  - langchain
  - langchain-core
  - langchain-openai
  - plotly
  - streamlit
  - python-dotenv
  - tabulate

